[2024-07-08T22:49:29.480+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-08T22:49:29.518+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl.create_tables manual__2024-07-08T22:49:26.141839+00:00 [queued]>
[2024-07-08T22:49:29.526+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl.create_tables manual__2024-07-08T22:49:26.141839+00:00 [queued]>
[2024-07-08T22:49:29.527+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-08T22:49:29.548+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): create_tables> on 2024-07-08 22:49:26.141839+00:00
[2024-07-08T22:49:29.574+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=43780) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-07-08T22:49:29.576+0000] {standard_task_runner.py:63} INFO - Started process 43786 to run task
[2024-07-08T22:49:29.580+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl', 'create_tables', 'manual__2024-07-08T22:49:26.141839+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/etl.py', '--cfg-path', '/tmp/tmp21x_26zm']
[2024-07-08T22:49:29.581+0000] {standard_task_runner.py:91} INFO - Job 7: Subtask create_tables
[2024-07-08T22:49:29.620+0000] {task_command.py:426} INFO - Running <TaskInstance: etl.create_tables manual__2024-07-08T22:49:26.141839+00:00 [running]> on host 8c15d98f81a6
[2024-07-08T22:49:29.727+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl' AIRFLOW_CTX_TASK_ID='create_tables' AIRFLOW_CTX_EXECUTION_DATE='2024-07-08T22:49:26.141839+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-08T22:49:26.141839+00:00'
[2024-07-08T22:49:29.730+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-08T22:49:29.748+0000] {base.py:84} INFO - Using connection ID 'my_postgres_conn' for task execution.
[2024-07-08T22:49:29.840+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-07-08T22:49:29.842+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-08T22:49:29.851+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=etl, task_id=create_tables, run_id=manual__2024-07-08T22:49:26.141839+00:00, execution_date=20240708T224926, start_date=20240708T224929, end_date=20240708T224929
[2024-07-08T22:49:29.915+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-07-08T22:49:29.938+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-07-08T22:49:29.949+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
