[2024-07-22T13:36:04.449+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-22T13:36:04.474+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: neon_pj.rename_column manual__2024-07-22T13:36:00.537938+00:00 [queued]>
[2024-07-22T13:36:04.480+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: neon_pj.rename_column manual__2024-07-22T13:36:00.537938+00:00 [queued]>
[2024-07-22T13:36:04.480+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-22T13:36:04.494+0000] {taskinstance.py:2330} INFO - Executing <Task(PostgresOperator): rename_column> on 2024-07-22 13:36:00.537938+00:00
[2024-07-22T13:36:04.503+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'neon_pj', 'rename_column', 'manual__2024-07-22T13:36:00.537938+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/neon_pj.py', '--cfg-path', '/tmp/tmpsz53izl8']
[2024-07-22T13:36:04.506+0000] {standard_task_runner.py:91} INFO - Job 5: Subtask rename_column
[2024-07-22T13:36:04.509+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=37061) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-07-22T13:36:04.510+0000] {standard_task_runner.py:63} INFO - Started process 37072 to run task
[2024-07-22T13:36:04.547+0000] {task_command.py:426} INFO - Running <TaskInstance: neon_pj.rename_column manual__2024-07-22T13:36:00.537938+00:00 [running]> on host 3c53d9be62d8
[2024-07-22T13:36:04.626+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='neon_pj' AIRFLOW_CTX_TASK_ID='rename_column' AIRFLOW_CTX_EXECUTION_DATE='2024-07-22T13:36:00.537938+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-22T13:36:00.537938+00:00'
[2024-07-22T13:36:04.628+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-22T13:36:04.628+0000] {sql.py:276} INFO - Executing: 
            create or replace view staging_chickens
            as
            select
            year,
            province,
            valu as number_of_chickens
            from chickens
            
[2024-07-22T13:36:04.635+0000] {base.py:84} INFO - Using connection ID 'neon_pj' for task execution.
[2024-07-22T13:36:04.643+0000] {base.py:84} INFO - Using connection ID 'neon_pj' for task execution.
[2024-07-22T13:36:04.729+0000] {sql.py:487} INFO - Running statement: 
            create or replace view staging_chickens
            as
            select
            year,
            province,
            valu as number_of_chickens
            from chickens
            , parameters: None
[2024-07-22T13:36:04.735+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-22T13:36:04.736+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 282, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 435, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 492, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UndefinedColumn: column "valu" does not exist
LINE 7:             valu as number_of_chickens
                    ^
HINT:  Perhaps you meant to reference the column "chickens.value".

[2024-07-22T13:36:04.744+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=neon_pj, task_id=rename_column, run_id=manual__2024-07-22T13:36:00.537938+00:00, execution_date=20240722T133600, start_date=20240722T133604, end_date=20240722T133604
[2024-07-22T13:36:04.761+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 5 for task rename_column (column "valu" does not exist
LINE 7:             valu as number_of_chickens
                    ^
HINT:  Perhaps you meant to reference the column "chickens.value".
; 37072)
[2024-07-22T13:36:04.805+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-22T13:36:04.818+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-22T13:36:04.824+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
