[2024-07-07T15:24:17.074+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-07T15:24:17.109+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dog_api_pipeline.get_don_api manual__2024-07-07T15:24:14.379129+00:00 [queued]>
[2024-07-07T15:24:17.115+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dog_api_pipeline.get_don_api manual__2024-07-07T15:24:14.379129+00:00 [queued]>
[2024-07-07T15:24:17.115+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-07T15:24:17.133+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): get_don_api> on 2024-07-07 15:24:14.379129+00:00
[2024-07-07T15:24:17.142+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=154255) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-07-07T15:24:17.142+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dog_api_pipeline', 'get_don_api', 'manual__2024-07-07T15:24:14.379129+00:00', '--job-id', '61', '--raw', '--subdir', 'DAGS_FOLDER/dog_api_pipeline.py', '--cfg-path', '/tmp/tmpf16ltxwc']
[2024-07-07T15:24:17.144+0000] {standard_task_runner.py:91} INFO - Job 61: Subtask get_don_api
[2024-07-07T15:24:17.144+0000] {standard_task_runner.py:63} INFO - Started process 154262 to run task
[2024-07-07T15:24:17.182+0000] {task_command.py:426} INFO - Running <TaskInstance: dog_api_pipeline.get_don_api manual__2024-07-07T15:24:14.379129+00:00 [running]> on host 64c03b0d339f
[2024-07-07T15:24:17.275+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dog_api_pipeline' AIRFLOW_CTX_TASK_ID='get_don_api' AIRFLOW_CTX_EXECUTION_DATE='2024-07-07T15:24:14.379129+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-07T15:24:14.379129+00:00'
[2024-07-07T15:24:17.277+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-07T15:24:17.926+0000] {dog_api_pipeline.py:13} INFO - <bound method Response.json of <Response [404]>>
[2024-07-07T15:24:17.927+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-07T15:24:17.927+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dog_api_pipeline.py", line 15, in _get_don_api
    json.dump(data,f)
  File "/usr/local/lib/python3.12/json/__init__.py", line 179, in dump
    for chunk in iterable:
  File "/usr/local/lib/python3.12/json/encoder.py", line 439, in _iterencode
    o = _default(o)
        ^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type method is not JSON serializable
[2024-07-07T15:24:17.935+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=dog_api_pipeline, task_id=get_don_api, run_id=manual__2024-07-07T15:24:14.379129+00:00, execution_date=20240707T152414, start_date=20240707T152417, end_date=20240707T152417
[2024-07-07T15:24:17.948+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 61 for task get_don_api (Object of type method is not JSON serializable; 154262)
[2024-07-07T15:24:17.969+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-07T15:24:17.985+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-07T15:24:17.993+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
